# Generated by Django 3.0.2 on 2020-01-10 03:31

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address_one', models.CharField(blank=True, max_length=60)),
                ('address_two', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(max_length=70)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('email', models.EmailField(max_length=80)),
                ('web_site', models.URLField(blank=True, max_length=100)),
                ('twitter', models.URLField(blank=True, max_length=80)),
                ('instagram', models.URLField(blank=True, max_length=80)),
                ('youtube', models.URLField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=80)),
                ('thc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('family', models.CharField(choices=[('S', 'Sativa'), ('I', 'Indica'), ('H', 'Hybrid')], max_length=6)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Grower')),
            ],
        ),
    ]
