# Generated by Django 3.0.2 on 2020-01-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grower',
            name='address_one',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='address_two',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='instagram',
            field=models.URLField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='twitter',
            field=models.URLField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='web_site',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='youtube',
            field=models.URLField(max_length=80, null=True),
        ),
    ]
