# Generated by Django 3.0.2 on 2020-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200110_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dispensary/static'),
        ),
        migrations.AlterField(
            model_name='grower',
            name='address_one',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='address_two',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='instagram',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='twitter',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='web_site',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grower',
            name='youtube',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
    ]
