# Generated by Django 3.0.2 on 2020-01-10 04:53

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20200110_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=70)),
                ('address_one', models.CharField(max_length=40)),
                ('address_two', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=80)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('date_of_birth', models.DateField(default=21)),
                ('phone', models.IntegerField()),
                ('phone_ext', models.IntegerField()),
                ('email', models.EmailField(max_length=80, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(choices=[(1.0, '1 g'), (3.5, '1/8 oz.'), (7.0, '1/4 oz.'), (14.0, '1/2 oz.'), (28.0, '1 oz.')], decimal_places=1, max_digits=2)),
                ('purchase_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Flower')),
            ],
            options={
                'ordering': ['-purchase_date', '-amount'],
            },
        ),
    ]
